#!/bin/sh

################################################################################
#
#  7z-install
#
#  Install/Update 7-Zip for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://7-zip.org/
#
#  Presquites:
#    - sed
#
#  Usage:
#    7z-install [<version>]
#
#  Example:
#    7z-install
#    7z-install 25.01
#    7z-install v25.01
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="ip7z"
GITHUB_REPO="7zip"
PROGRAM_ID="7z"
PROGRAM_EXEC="7zz"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	_INSTALL_VERSION=$(echo "${INSTALL_VERSION}" | sed 's/\.//')
	BIN_ARCH_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/${INSTALL_VERSION}/7z${_INSTALL_VERSION}-linux-x64.tar.xz"
	BIN_ARCH_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/${INSTALL_VERSION}/7z${_INSTALL_VERSION}-linux-arm64.tar.xz"
	BIN_ARCH_TMP_FILE="${TEMP_TARGET}.tar.xz"
	download_uri_per_arch "${BIN_ARCH_URI_AMD64}" "${BIN_ARCH_URI_ARM64}" "${BIN_ARCH_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${BIN_ARCH_TMP_FILE}" "tar" "${TEMP_TARGET}"
	remove_item "${BIN_ARCH_TMP_FILE}"
	move_item "${TEMP_TARGET}" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
symlink_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC}" "${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
