#!/bin/sh

################################################################################
#
#  agave-install
#
#  Install/Update Agave for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://www.anza.xyz/
#
#  Presquites:
#  - Rust
#  - clang protobuf-compiler
#  - libclang-dev libprotobuf-dev libssl-dev libudev-dev zlib1g-dev
#
#  Usage:
#    agave-install [<version>]
#
#  Example:
#    agave-install
#    agave-install 3.0.12
#    agave-install v3.0.12
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="anza-xyz"
GITHUB_REPO="agave"
PROGRAM_ID="agave"
PROGRAM_EXEC="solana"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env "${PROGRAM_ID}" "${INSTALL_VERSION}"
INSTALL_ROOT="${HOME}/.local/share/solana"
INSTALL_TARGET="${INSTALL_ROOT}/install/releases/${INSTALL_VERSION}"
ACTIVE_TARGET="${INSTALL_ROOT}/install/active_release"
mkdir -p "${INSTALL_ROOT}/install/releases"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	SRC_ARCH_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/archive/refs/tags/v${INSTALL_VERSION}.tar.gz"
	SRC_ARCH_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/archive/refs/tags/v${INSTALL_VERSION}.tar.gz"
	SRC_ARCH_TMP_FILE="${TEMP_TARGET}.tar.gz"
	download_uri_per_arch "${SRC_ARCH_URI_AMD64}" "${SRC_ARCH_URI_ARM64}" "${SRC_ARCH_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${SRC_ARCH_TMP_FILE}" "tar" "${TEMP_TARGET}"
	remove_item "${SRC_ARCH_TMP_FILE}"
	move_item "${TEMP_TARGET}/${GITHUB_REPO}-${INSTALL_VERSION}" "${TEMP_TARGET}/solana-release"
	cd "${TEMP_TARGET}/solana-release"
	./scripts/cargo-install-all.sh .
	move_item "${TEMP_TARGET}" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
symlink_item_overwrite "${INSTALL_TARGET}/solana-release" "${ACTIVE_TARGET}"
cat << EOF > "${INSTALL_ROOT}/env.sh"
export PATH="\$HOME/.local/share/solana/install/active_release/bin:\$PATH"
EOF
append_text_idempotent "# solana" "${USER_PROFILE_RC}"
append_text_idempotent ". \"${INSTALL_ROOT}/env.sh\"" "${USER_PROFILE_RC}"
