#!/bin/sh

################################################################################
#
#  base-node-install
#
#  Install/Update Base Node for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://www.base.org/
#
#  Usage:
#    base-node-install [<version>]
#
#  Example:
#    base-node-install
#    base-node-install 0.9.1
#    base-node-install v0.9.1
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="base"
GITHUB_REPO="base"
PROGRAM_ID="base-node"
PROGRAM_EXEC_1="base-reth-node"
SYSTEM_EXEC__1="base-reth"
PROGRAM_EXEC_2="base-consensus"
SYSTEM_EXEC__2="base-node"
PROGRAM_EXEC_3="basectl"
SYSTEM_EXEC__3="basectl"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_ARCH_URI_AMD64_1="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/base-reth-node-v${INSTALL_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
	BIN_ARCH_URI_ARM64_1="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/base-reth-node-v${INSTALL_VERSION}-aarch64-unknown-linux-gnu.tar.gz"
	BIN_ARCH_TMP_FILE_1="${TEMP_ROOT}/${PROGRAM_EXEC_1}.tar.gz"
	BIN_ARCH_URI_AMD64_2="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/base-consensus-v${INSTALL_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
	BIN_ARCH_URI_ARM64_2="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/base-consensus-v${INSTALL_VERSION}-aarch64-unknown-linux-gnu.tar.gz"
	BIN_ARCH_TMP_FILE_2="${TEMP_ROOT}/${PROGRAM_EXEC_2}.tar.gz"
	BIN_ARCH_URI_AMD64_3="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/basectl-v${INSTALL_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
	BIN_ARCH_URI_ARM64_3="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/basectl-v${INSTALL_VERSION}-aarch64-unknown-linux-gnu.tar.gz"
	BIN_ARCH_TMP_FILE_3="${TEMP_ROOT}/${PROGRAM_EXEC_3}.tar.gz"
	download_uri_per_arch "${BIN_ARCH_URI_AMD64_1}" "${BIN_ARCH_URI_ARM64_1}" "${BIN_ARCH_TMP_FILE_1}"
	download_uri_per_arch "${BIN_ARCH_URI_AMD64_2}" "${BIN_ARCH_URI_ARM64_2}" "${BIN_ARCH_TMP_FILE_2}"
	download_uri_per_arch "${BIN_ARCH_URI_AMD64_3}" "${BIN_ARCH_URI_ARM64_3}" "${BIN_ARCH_TMP_FILE_3}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${BIN_ARCH_TMP_FILE_1}" "tar" "${TEMP_TARGET}"
	extract_archive "${BIN_ARCH_TMP_FILE_2}" "tar" "${TEMP_TARGET}"
	extract_archive "${BIN_ARCH_TMP_FILE_3}" "tar" "${TEMP_TARGET}"
	remove_item "${BIN_ARCH_TMP_FILE_1}"
	remove_item "${BIN_ARCH_TMP_FILE_2}"
	remove_item "${BIN_ARCH_TMP_FILE_3}"
	move_item "${TEMP_TARGET}" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
symlink_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC_1}" "${SYSTEM_BIN_ROOT}/${SYSTEM_EXEC__1}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC_2}" "${SYSTEM_BIN_ROOT}/${SYSTEM_EXEC__2}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC_3}" "${SYSTEM_BIN_ROOT}/${SYSTEM_EXEC__3}"
