#!/bin/sh

################################################################################
#
#  bsc-reth-install
#
#  Install/Update BSC Reth for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Presquites:
#  - Rust
#
#  Homepage: https://www.bnbchain.org/en/bnb-smart-chain
#
#  Usage:
#    bsc-reth-install [<version>]
#
#  Example:
#    bsc-reth-install
#    bsc-reth-install 1.0.0
#    bsc-reth-install v1.0.0
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -e

# Application info
GITHUB_OWNER="bnb-chain"
GITHUB_REPO="reth-bsc"
PROGRAM_ID="bsc-reth"
PROGRAM_EXEC="reth-bsc"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	SRC_ARCH_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/archive/refs/tags/v${INSTALL_VERSION}.tar.gz"
	SRC_ARCH_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/archive/refs/tags/v${INSTALL_VERSION}.tar.gz"
	SRC_ARCH_TMP_FILE="${TEMP_TARGET}.tar.gz"
	download_uri_per_arch "${SRC_ARCH_URI_AMD64}" "${SRC_ARCH_URI_ARM64}" "${SRC_ARCH_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${SRC_ARCH_TMP_FILE}" "tar" "${TEMP_TARGET}"
	remove_item "${SRC_ARCH_TMP_FILE}"
	cd "${TEMP_TARGET}/${GITHUB_REPO}-${INSTALL_VERSION}"
	make maxperf
	remove_item "${TEMP_TARGET}/${GITHUB_REPO}-${INSTALL_VERSION}/target/maxperf/build"
	remove_item "${TEMP_TARGET}/${GITHUB_REPO}-${INSTALL_VERSION}/target/maxperf/deps"
	remove_item "${TEMP_TARGET}/${GITHUB_REPO}-${INSTALL_VERSION}/target/maxperf/examples"
	remove_item "${TEMP_TARGET}/${GITHUB_REPO}-${INSTALL_VERSION}/target/maxperf/incremental"
	move_item "${TEMP_TARGET}/${GITHUB_REPO}-${INSTALL_VERSION}/target/maxperf" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
symlink_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC}" "${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
