#!/bin/sh

################################################################################
#
#  geth-install
#
#  Install/Update Go-ethereum for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://geth.ethereum.org/
#
#  Presquites:
#  - Go
#
#  Usage:
#    geth-install [<version>]
#
#  Example:
#    geth-install
#    geth-install 1.16.7
#    geth-install v1.16.7
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="ethereum"
GITHUB_REPO="go-ethereum"
PROGRAM_ID="geth"
PROGRAM_EXEC="geth"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	SRC_ARCH_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/archive/refs/tags/v${INSTALL_VERSION}.tar.gz"
	SRC_ARCH_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/archive/refs/tags/v${INSTALL_VERSION}.tar.gz"
	SRC_ARCH_TMP_FILE="${TEMP_TARGET}.tar.gz"
	download_uri_per_arch "${SRC_ARCH_URI_AMD64}" "${SRC_ARCH_URI_ARM64}" "${SRC_ARCH_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${SRC_ARCH_TMP_FILE}" "tar" "${TEMP_TARGET}"
	remove_item "${SRC_ARCH_TMP_FILE}"
	cd "${TEMP_TARGET}/${GITHUB_REPO}-${INSTALL_VERSION}"
	go run build/ci.go install
	move_item "${TEMP_TARGET}/${GITHUB_REPO}-${INSTALL_VERSION}/build/bin" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
symlink_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC}" "${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
