#!/bin/sh

################################################################################
#
#  gitea-install
#
#  Install/Update Gitea for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://gitea.com/
#
#  Usage:
#    gitea-install [<version>]
#
#  Example:
#    gitea-install
#    gitea-install 1.25.2
#    gitea-install v1.25.2
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="go-gitea"
GITHUB_REPO="gitea"
PROGRAM_ID="gitea"
PROGRAM_EXEC="gitea"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/gitea-${INSTALL_VERSION}-linux-amd64"
	BIN_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/gitea-${INSTALL_VERSION}-linux-arm64"
	BIN_TMP_FILE="${TEMP_TARGET}.bin"
	download_uri_per_arch "${BIN_URI_AMD64}" "${BIN_URI_ARM64}" "${BIN_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	make_executable "${BIN_TMP_FILE}"
	move_item "${BIN_TMP_FILE}" "${TEMP_TARGET}/${PROGRAM_EXEC}"
	move_item "${TEMP_TARGET}" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
symlink_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC}" "${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
