#!/bin/sh

################################################################################
#
#  gitea-install
#
#  Install/Update Gitea for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://gitea.com/
#
#  Usage:
#    gitea-install [<version>]
#
#  Example:
#    gitea-install
#    gitea-install 1.25.2
#    gitea-install v1.25.2
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

# Application info
GITHUB_OWNER="go-gitea"
GITHUB_REPO="gitea"
PROGRAM_ID="gitea"
PROGRAM_EXEC="gitea"

set -ex

# Determine version to install
if [ -z "$1" ]; then
	LATEST_VERSION="$(curl https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/releases/latest | jq -r .tag_name)"
else
	LATEST_VERSION="$1"
fi
LATEST_VERSION="${LATEST_VERSION#v}"

# Installation environment
USERID="$(id -u)"
ARCH="$(uname -m)"
if [ "${USERID}" -eq 0 ]; then
	INSTALL_ROOT="/usr/local/share/${PROGRAM_ID}"
else
	INSTALL_ROOT="${HOME}/.local/share/${PROGRAM_ID}"
fi
INSTALL_TARGET="${INSTALL_ROOT}/${PROGRAM_ID}-v${LATEST_VERSION}"
ACTIVE_TARGET="${INSTALL_ROOT}/active-release"
SYSTEM_BIN_TARGET="/usr/local/bin"

mkdir -p "${INSTALL_ROOT}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${LATEST_VERSION}/gitea-${LATEST_VERSION}-linux-amd64"
	BIN_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${LATEST_VERSION}/gitea-${LATEST_VERSION}-linux-arm64"
	BIN_TMP_FILE="/tmp/${PROGRAM_ID}-v${LATEST_VERSION}.bin"

	if [ "${ARCH}" = "x86_64" ] || [ "${ARCH}" = "amd64" ]; then
		wget "${BIN_URI_AMD64}" -O "${BIN_TMP_FILE}"
	elif [ "${ARCH}" = "aarch64" ] || [ "${ARCH}" = "arm64" ]; then
		wget "${BIN_URI_ARM64}" -O "${BIN_TMP_FILE}"
	else
		echo "Unsupported architecture: ${ARCH}"
		exit 1
	fi

	mkdir "${INSTALL_TARGET}"
	chmod +x "${BIN_TMP_FILE}"
	mv "${BIN_TMP_FILE}" "${INSTALL_TARGET}/${PROGRAM_EXEC}"
fi

# Set active release
if [ -f "${ACTIVE_TARGET}" ] || [ -d "${ACTIVE_TARGET}" ] || [ -L "${ACTIVE_TARGET}" ]; then
	rm -r "${ACTIVE_TARGET}"
fi
ln -s "${INSTALL_TARGET}" "${ACTIVE_TARGET}"

# Create symlink for quick access
ACTIVE_TARGET_BIN="${ACTIVE_TARGET}/${PROGRAM_EXEC}"
SYSTEM_BIN_TARGET_BIN="${SYSTEM_BIN_TARGET}/${PROGRAM_EXEC}"
if [ "${USERID}" -eq 0 ] && [ -f "${ACTIVE_TARGET_BIN}" ]; then
	if [ -f "${SYSTEM_BIN_TARGET_BIN}" ] || [ -d "${SYSTEM_BIN_TARGET_BIN}" ] || [ -L "${SYSTEM_BIN_TARGET_BIN}" ]; then
		rm -r "${SYSTEM_BIN_TARGET_BIN}"
	fi
	ln -s "${ACTIVE_TARGET_BIN}" "${SYSTEM_BIN_TARGET_BIN}"
fi
