#!/bin/sh

################################################################################
#
#  go-install
#
#  Install/Update Go for current user. This also works as a version manager.
#
#  Homepage: https://go.dev/
#
#  Usage:
#    go-install <version>
#
#  Example:
#    go-install 1.24.7
#    go-install v1.24.7
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
PROGRAM_ID="go"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
normalize_install_version "$1"
init_install_env "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_ARCH_URI_AMD64="https://go.dev/dl/go${INSTALL_VERSION}.linux-amd64.tar.gz"
	BIN_ARCH_URI_ARM64="https://go.dev/dl/go${INSTALL_VERSION}.linux-arm64.tar.gz"
	BIN_ARCH_TMP_FILE="${TEMP_TARGET}.tar.gz"
	download_uri_per_arch "${BIN_ARCH_URI_AMD64}" "${BIN_ARCH_URI_ARM64}" "${BIN_ARCH_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${BIN_ARCH_TMP_FILE}" "tar" "${TEMP_TARGET}"
	remove_item "${BIN_ARCH_TMP_FILE}"
	move_item "${TEMP_TARGET}/go" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
symlink_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
cat << EOF > "${INSTALL_ROOT}/env.sh"
export GOROOT="${ACTIVE_TARGET}"
export GOPATH="\$HOME/go"
export PATH="\$GOROOT/bin:\$GOPATH/bin:\$PATH"
EOF
append_text_idempotent "# go" "${USER_PROFILE_RC}"
append_text_idempotent ". \"${INSTALL_ROOT}/env.sh\"" "${USER_PROFILE_RC}"
