#!/bin/sh

################################################################################
#
#  jellyfin-install
#
#  Install/Update Jellyfin for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://jellyfin.org/
#
#  Usage:
#    jellyfin-install [<version>]
#
#  Example:
#    jellyfin-install
#    jellyfin-install 10.11.5
#    jellyfin-install v10.11.5
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="jellyfin"
GITHUB_REPO="jellyfin"
PROGRAM_ID="jellyfin"
PROGRAM_EXEC="jellyfin"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_ARCH_URI_AMD64="https://repo.jellyfin.org/files/server/linux/stable/v${INSTALL_VERSION}/amd64/jellyfin_${INSTALL_VERSION}-amd64.tar.xz"
	BIN_ARCH_URI_ARM64="https://repo.jellyfin.org/files/server/linux/stable/v${INSTALL_VERSION}/arm64/jellyfin_${INSTALL_VERSION}-arm64.tar.xz"
	BIN_ARCH_TMP_FILE="${TEMP_TARGET}.tar.xz"
	download_uri_per_arch "${BIN_ARCH_URI_AMD64}" "${BIN_ARCH_URI_ARM64}" "${BIN_ARCH_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${BIN_ARCH_TMP_FILE}" "tar" "${TEMP_TARGET}"
	remove_item "${BIN_ARCH_TMP_FILE}"
	move_item "${TEMP_TARGET}/jellyfin" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
symlink_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC}" "${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
