#!/bin/sh

################################################################################
#
#  nvm-install
#
#  Install/Update Node Version Manager for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://github.com/nvm-sh/nvm
#
#  Usage:
#    nvm-install [<version>]
#
#  Example:
#    nvm-install
#    nvm-install 0.40.3
#    nvm-install v0.40.3
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="nvm-sh"
GITHUB_REPO="nvm"
PROGRAM_ID="nvm"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/v${INSTALL_VERSION}/install.sh" | bash
