#!/bin/sh

################################################################################
#
#  op-node-install
#
#  Install/Update op-node for current user. This also works as a version manager.
#
#  Presquites:
#  - Go
#
#  Homepage: https://www.optimism.io/
#
#  Usage:
#    op-node-install <version>
#
#  Example:
#    op-node-install 1.14.1
#    op-node-install v1.14.1
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

# Application info
GITHUB_OWNER="ethereum-optimism"
GITHUB_REPO="optimism"
PROGRAM_ID="op-node"
PROGRAM_EXEC="op-node"

set -ex

# Determine version to install
if [ -z "$1" ]; then
	echo "Error: Version must be explicitly specified"
	exit 1
else
	LATEST_VERSION="$1"
fi
LATEST_VERSION="${LATEST_VERSION#v}"

# Installation environment
USERID="$(id -u)"
ARCH="$(uname -m)"
if [ "${USERID}" -eq 0 ]; then
	INSTALL_ROOT="/usr/local/share/${PROGRAM_ID}"
else
	INSTALL_ROOT="${HOME}/.local/share/${PROGRAM_ID}"
fi
INSTALL_TARGET="${INSTALL_ROOT}/${PROGRAM_ID}-v${LATEST_VERSION}"
ACTIVE_TARGET="${INSTALL_ROOT}/active-release"
SYSTEM_BIN_TARGET="/usr/local/bin"

mkdir -p "${INSTALL_ROOT}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	SRC_ARCH_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/archive/refs/tags/v${LATEST_VERSION}.tar.gz"
	SRC_ARCH_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/archive/refs/tags/v${LATEST_VERSION}.tar.gz"
	SRC_ARCH_TMP_FILE="/tmp/${PROGRAM_ID}-v${LATEST_VERSION}.tar.gz"

	if [ "${ARCH}" = "x86_64" ] || [ "${ARCH}" = "amd64" ]; then
		curl -fSL "${SRC_ARCH_URI_AMD64}" -o "${SRC_ARCH_TMP_FILE}"
	elif [ "${ARCH}" = "aarch64" ] || [ "${ARCH}" = "arm64" ]; then
		curl -fSL "${SRC_ARCH_URI_ARM64}" -o "${SRC_ARCH_TMP_FILE}"
	else
		echo "Unsupported architecture: ${ARCH}"
		exit 1
	fi

	TEMP_TARGET="/tmp/${PROGRAM_ID}-v${LATEST_VERSION}"
	mkdir "${TEMP_TARGET}"
	tar -x -v -f "${SRC_ARCH_TMP_FILE}" -C "${TEMP_TARGET}"
	rm "${SRC_ARCH_TMP_FILE}"
	cd "${TEMP_TARGET}/${GITHUB_REPO}-${LATEST_VERSION}"
	cd "op-node"
	env GO111MODULE=on GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v -ldflags "-X main.GitCommit=release -X main.GitDate=$(date +%s) -X github.com/ethereum-optimism/optimism/op-node/version.Version=v${LATEST_VERSION} -X github.com/ethereum-optimism/optimism/op-node/version.Meta=" -o ./bin/op-node ./cmd
	mv "${TEMP_TARGET}/${GITHUB_REPO}-${LATEST_VERSION}/op-node/bin" "${INSTALL_TARGET}"
	rm -r "${TEMP_TARGET}"
fi

# Set active release
if [ -f "${ACTIVE_TARGET}" ] || [ -d "${ACTIVE_TARGET}" ] || [ -L "${ACTIVE_TARGET}" ]; then
	rm -r "${ACTIVE_TARGET}"
fi
ln -s "${INSTALL_TARGET}" "${ACTIVE_TARGET}"

# Create symlink for quick access
ACTIVE_TARGET_BIN="${ACTIVE_TARGET}/${PROGRAM_EXEC}"
SYSTEM_BIN_TARGET_BIN="${SYSTEM_BIN_TARGET}/${PROGRAM_ID}"
if [ "${USERID}" -eq 0 ] && [ -f "${ACTIVE_TARGET_BIN}" ]; then
	if [ -f "${SYSTEM_BIN_TARGET_BIN}" ] || [ -d "${SYSTEM_BIN_TARGET_BIN}" ] || [ -L "${SYSTEM_BIN_TARGET_BIN}" ]; then
		rm -r "${SYSTEM_BIN_TARGET_BIN}"
	fi
	ln -s "${ACTIVE_TARGET_BIN}" "${SYSTEM_BIN_TARGET_BIN}"
fi
