#!/bin/sh

################################################################################
#
#  pnpm-install
#
#  Install/Update PNPM for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://pnpm.io/
#
#  Usage:
#    pnpm-install [<version>]
#
#  Example:
#    pnpm-install
#    pnpm-install 10.25.0
#    pnpm-install v10.25.0
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="pnpm"
GITHUB_REPO="pnpm"
PROGRAM_ID="pnpm"
PROGRAM_EXEC="pnpm"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/pnpm-linux-x64"
	BIN_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/pnpm-linux-arm64"
	BIN_TMP_FILE="${TEMP_TARGET}.bin"
	download_uri_per_arch "${BIN_URI_AMD64}" "${BIN_URI_ARM64}" "${BIN_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	make_executable "${BIN_TMP_FILE}"
	move_item "${BIN_TMP_FILE}" "${TEMP_TARGET}/${PROGRAM_EXEC}"
	move_item "${TEMP_TARGET}" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
symlink_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC}" "${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
