#!/bin/sh

################################################################################
#
#  prysm-install
#
#  Install/Update Prysm for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://www.offchainlabs.com/prysm
#
#  Usage:
#    prysm-install [<version>]
#
#  Example:
#    prysm-install
#    prysm-install 7.1.1
#    prysm-install v7.1.1
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="OffchainLabs"
GITHUB_REPO="prysm"
PROGRAM_ID="prysm"
PROGRAM_EXEC_1="beacon-chain"
SYSTEM_EXEC__1="prysm-beacon"
PROGRAM_EXEC_2="client-stats"
SYSTEM_EXEC__2="prysm-stats"
PROGRAM_EXEC_3="prysmctl"
SYSTEM_EXEC__3="prysmctl"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_URI_AMD64_1="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/beacon-chain-v${INSTALL_VERSION}-modern-linux-amd64"
	BIN_URI_ARM64_1="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/beacon-chain-v${INSTALL_VERSION}-linux-arm64"
	BIN_TMP_FILE_1="${TEMP_ROOT}/${PROGRAM_EXEC_1}.bin"
	BIN_URI_AMD64_2="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/client-stats-v${INSTALL_VERSION}-linux-amd64"
	BIN_URI_ARM64_2="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/client-stats-v${INSTALL_VERSION}-linux-arm64"
	BIN_TMP_FILE_2="${TEMP_ROOT}/${PROGRAM_EXEC_2}.bin"
	BIN_URI_AMD64_3="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/prysmctl-v${INSTALL_VERSION}-linux-amd64"
	BIN_URI_ARM64_3="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/prysmctl-v${INSTALL_VERSION}-linux-arm64"
	BIN_TMP_FILE_3="${TEMP_ROOT}/${PROGRAM_EXEC_3}.bin"
	download_uri_per_arch "${BIN_URI_AMD64_1}" "${BIN_URI_ARM64_1}" "${BIN_TMP_FILE_1}"
	download_uri_per_arch "${BIN_URI_AMD64_2}" "${BIN_URI_ARM64_2}" "${BIN_TMP_FILE_2}"
	download_uri_per_arch "${BIN_URI_AMD64_3}" "${BIN_URI_ARM64_3}" "${BIN_TMP_FILE_3}"
	create_dir "${TEMP_TARGET}"
	make_executable "${BIN_TMP_FILE_1}"
	make_executable "${BIN_TMP_FILE_2}"
	make_executable "${BIN_TMP_FILE_3}"
	move_item "${BIN_TMP_FILE_1}" "${TEMP_TARGET}/${PROGRAM_EXEC_1}"
	move_item "${BIN_TMP_FILE_2}" "${TEMP_TARGET}/${PROGRAM_EXEC_2}"
	move_item "${BIN_TMP_FILE_3}" "${TEMP_TARGET}/${PROGRAM_EXEC_3}"
	move_item "${TEMP_TARGET}" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
symlink_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC_1}" "${SYSTEM_BIN_ROOT}/${SYSTEM_EXEC__1}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC_2}" "${SYSTEM_BIN_ROOT}/${SYSTEM_EXEC__2}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC_3}" "${SYSTEM_BIN_ROOT}/${SYSTEM_EXEC__3}"
