#!/bin/sh

################################################################################
#
#  prysm-install
#
#  Install/Update Prysm for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://www.offchainlabs.com/prysm
#
#  Usage:
#    prysm-install [<version>]
#
#  Example:
#    prysm-install
#    prysm-install 7.1.1
#    prysm-install v7.1.1
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

# Application info
GITHUB_OWNER="OffchainLabs"
GITHUB_REPO="prysm"
PROGRAM_ID="prysm"
PROGRAM_EXEC="beacon-chain"

set -ex

# Determine version to install
if [ -z "$1" ]; then
	LATEST_VERSION="$(curl https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/releases/latest | jq -r .tag_name)"
else
	LATEST_VERSION="$1"
fi
LATEST_VERSION="${LATEST_VERSION#v}"

# Installation environment
USERID="$(id -u)"
ARCH="$(uname -m)"
if [ "${USERID}" -eq 0 ]; then
	INSTALL_ROOT="/usr/local/share/${PROGRAM_ID}"
else
	INSTALL_ROOT="${HOME}/.local/share/${PROGRAM_ID}"
fi
INSTALL_TARGET="${INSTALL_ROOT}/${PROGRAM_ID}-v${LATEST_VERSION}"
ACTIVE_TARGET="${INSTALL_ROOT}/active-release"
SYSTEM_BIN_TARGET="/usr/local/bin"

mkdir -p "${INSTALL_ROOT}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${LATEST_VERSION}/beacon-chain-v${LATEST_VERSION}-modern-linux-amd64"
	BIN_URI2_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${LATEST_VERSION}/client-stats-v${LATEST_VERSION}-linux-amd64"
	BIN_URI3_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${LATEST_VERSION}/prysmctl-v${LATEST_VERSION}-linux-amd64"
	BIN_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${LATEST_VERSION}/beacon-chain-v${LATEST_VERSION}-linux-arm64"
	BIN_URI2_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${LATEST_VERSION}/client-stats-v${LATEST_VERSION}-linux-arm64"
	BIN_URI3_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${LATEST_VERSION}/prysmctl-v${LATEST_VERSION}-linux-arm64"
	BIN_TMP_FILE="/tmp/${PROGRAM_ID}-v${LATEST_VERSION}.bin"
	BIN_TMP_FILE2="/tmp/client-stats-v${LATEST_VERSION}.bin"
	BIN_TMP_FILE3="/tmp/prysmctl-v${LATEST_VERSION}.bin"

	if [ "${ARCH}" = "x86_64" ] || [ "${ARCH}" = "amd64" ]; then
		curl -fSL "${BIN_URI_AMD64}" -o "${BIN_TMP_FILE}"
		curl -fSL "${BIN_URI2_AMD64}" -o "${BIN_TMP_FILE2}"
		curl -fSL "${BIN_URI3_AMD64}" -o "${BIN_TMP_FILE3}"
	elif [ "${ARCH}" = "aarch64" ] || [ "${ARCH}" = "arm64" ]; then
		curl -fSL "${BIN_URI_ARM64}" -o "${BIN_TMP_FILE}"
		curl -fSL "${BIN_URI2_ARM64}" -o "${BIN_TMP_FILE2}"
		curl -fSL "${BIN_URI3_ARM64}" -o "${BIN_TMP_FILE3}"
	else
		echo "Unsupported architecture: ${ARCH}"
		exit 1
	fi

	mkdir "${INSTALL_TARGET}"
	chmod +x "${BIN_TMP_FILE}"
	chmod +x "${BIN_TMP_FILE2}"
	chmod +x "${BIN_TMP_FILE3}"
	mv "${BIN_TMP_FILE}" "${INSTALL_TARGET}/${PROGRAM_EXEC}"
	mv "${BIN_TMP_FILE2}" "${INSTALL_TARGET}/client-stats"
	mv "${BIN_TMP_FILE3}" "${INSTALL_TARGET}/prysmctl"
fi

# Set active release
if [ -f "${ACTIVE_TARGET}" ] || [ -d "${ACTIVE_TARGET}" ] || [ -L "${ACTIVE_TARGET}" ]; then
	rm -r "${ACTIVE_TARGET}"
fi
ln -s "${INSTALL_TARGET}" "${ACTIVE_TARGET}"

# Create symlink for quick access
ACTIVE_TARGET_BIN="${ACTIVE_TARGET}/${PROGRAM_EXEC}"
SYSTEM_BIN_TARGET_BIN="${SYSTEM_BIN_TARGET}/${PROGRAM_ID}"
if [ "${USERID}" -eq 0 ] && [ -f "${ACTIVE_TARGET_BIN}" ]; then
	if [ -f "${SYSTEM_BIN_TARGET_BIN}" ] || [ -d "${SYSTEM_BIN_TARGET_BIN}" ] || [ -L "${SYSTEM_BIN_TARGET_BIN}" ]; then
		rm -r "${SYSTEM_BIN_TARGET_BIN}"
	fi
	ln -s "${ACTIVE_TARGET_BIN}" "${SYSTEM_BIN_TARGET_BIN}"
fi
