#!/bin/sh

################################################################################
#
#  stashbox-install
#
#  Install/Update Stash Box for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://stashapp.cc/
#
#  Usage:
#    stashbox-install [<version>]
#
#  Example:
#    stashbox-install
#    stashbox-install 0.7.7
#    stashbox-install v0.7.7
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

# Application info
GITHUB_OWNER="stashapp"
GITHUB_REPO="stash-box"
PROGRAM_ID="stashbox"
PROGRAM_EXEC="stash-box"

set -ex

# Determine version to install
if [ -z "$1" ]; then
	LATEST_VERSION="$(curl https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/releases/latest | jq -r .tag_name)"
else
	LATEST_VERSION="$1"
fi
LATEST_VERSION="${LATEST_VERSION#v}"

# Installation environment
USERID="$(id -u)"
ARCH="$(uname -m)"
if [ "${USERID}" -eq 0 ]; then
	INSTALL_ROOT="/usr/local/share/${PROGRAM_ID}"
	SYSTEM_BIN_ROOT="/usr/local/bin"
else
	INSTALL_ROOT="${HOME}/.local/share/${PROGRAM_ID}"
	SYSTEM_BIN_ROOT="${HOME}/.local/bin"
fi
INSTALL_TARGET="${INSTALL_ROOT}/${PROGRAM_ID}-v${LATEST_VERSION}"
ACTIVE_TARGET="${INSTALL_ROOT}/active-release"

if [ ! -d "${INSTALL_ROOT}" ]; then
	mkdir -p "${INSTALL_ROOT}"
fi
if [ ! -d "${SYSTEM_BIN_ROOT}" ]; then
	mkdir -p "${SYSTEM_BIN_ROOT}"
fi

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${LATEST_VERSION}/stash-box-linux"
	BIN_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${LATEST_VERSION}/stash-box-linux"
	BIN_TMP_FILE="/tmp/${PROGRAM_ID}-v${LATEST_VERSION}.bin"

	if [ "${ARCH}" = "x86_64" ] || [ "${ARCH}" = "amd64" ]; then
		curl -fSL "${BIN_URI_AMD64}" -o "${BIN_TMP_FILE}"
	elif [ "${ARCH}" = "aarch64" ] || [ "${ARCH}" = "arm64" ]; then
		echo "Unsupported architecture: ${ARCH}"
		exit 1
	else
		echo "Unsupported architecture: ${ARCH}"
		exit 1
	fi

	mkdir "${INSTALL_TARGET}"
	chmod +x "${BIN_TMP_FILE}"
	mv "${BIN_TMP_FILE}" "${INSTALL_TARGET}/${PROGRAM_EXEC}"
fi

# Set active release
if [ -f "${ACTIVE_TARGET}" ] || [ -d "${ACTIVE_TARGET}" ] || [ -L "${ACTIVE_TARGET}" ]; then
	rm -r "${ACTIVE_TARGET}"
fi
ln -s "${INSTALL_TARGET}" "${ACTIVE_TARGET}"

# Create symlink for quick access
ACTIVE_TARGET_BIN="${ACTIVE_TARGET}/${PROGRAM_EXEC}"
SYSTEM_BIN_TARGET_BIN="${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
if [ -f "${ACTIVE_TARGET_BIN}" ]; then
	if [ -f "${SYSTEM_BIN_TARGET_BIN}" ] || [ -d "${SYSTEM_BIN_TARGET_BIN}" ] || [ -L "${SYSTEM_BIN_TARGET_BIN}" ]; then
		rm -r "${SYSTEM_BIN_TARGET_BIN}"
	fi
	ln -s "${ACTIVE_TARGET_BIN}" "${SYSTEM_BIN_TARGET_BIN}"
fi
