#!/bin/sh

################################################################################
#
#  sui-install
#
#  Install/Update Sui for current user. This also works as a version manager.
#
#  Homepage: https://www.sui.io/
#
#  Usage:
#    sui-install <version>
#
#  Example:
#    sui-install 1.62.1
#    sui-install v1.62.1
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="MystenLabs"
GITHUB_REPO="sui"
PROGRAM_ID="sui"
PROGRAM_EXEC="sui"
PROGRAM_EXEC_1="sui-bridge"
SYSTEM_EXEC__1="sui-bridge"
PROGRAM_EXEC_2="sui-debug"
SYSTEM_EXEC__2="sui-debug"
PROGRAM_EXEC_3="sui-node"
SYSTEM_EXEC__3="sui-node"
PROGRAM_EXEC_4="sui-tool"
SYSTEM_EXEC__4="sui-tool"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
normalize_install_version "$1"
init_install_env_desktop "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_ARCH_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/mainnet-v${INSTALL_VERSION}/sui-mainnet-v${INSTALL_VERSION}-ubuntu-x86_64.tgz"
	BIN_ARCH_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/mainnet-v${INSTALL_VERSION}/sui-mainnet-v${INSTALL_VERSION}-ubuntu-aarch64.tgz"
	BIN_ARCH_TMP_FILE="${TEMP_TARGET}.tgz"
	download_uri_per_arch "${BIN_ARCH_URI_AMD64}" "${BIN_ARCH_URI_ARM64}" "${BIN_ARCH_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${BIN_ARCH_TMP_FILE}" "tar" "${TEMP_TARGET}"
	remove_item "${BIN_ARCH_TMP_FILE}"
	move_item "${TEMP_TARGET}" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
symlink_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC}" "${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC_1}" "${SYSTEM_BIN_ROOT}/${SYSTEM_EXEC__1}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC_2}" "${SYSTEM_BIN_ROOT}/${SYSTEM_EXEC__2}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC_3}" "${SYSTEM_BIN_ROOT}/${SYSTEM_EXEC__3}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC_4}" "${SYSTEM_BIN_ROOT}/${SYSTEM_EXEC__4}"
