#!/bin/sh

################################################################################
#
#  syncthdiscv-install
#
#  Install/Update Syncthing Discovery Server for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://syncthing.net/
#
#  Usage:
#    syncthdiscv-install [<version>]
#
#  Example:
#    syncthdiscv-install
#    syncthdiscv-install 2.0.12
#    syncthdiscv-install v2.0.12
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="syncthing"
GITHUB_REPO="discosrv"
PROGRAM_ID="syncthdiscv"
PROGRAM_EXEC="stdiscosrv"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_ARCH_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/stdiscosrv-linux-amd64-v${INSTALL_VERSION}.tar.gz"
	BIN_ARCH_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/stdiscosrv-linux-arm64-v${INSTALL_VERSION}.tar.gz"
	BIN_ARCH_TMP_FILE="${TEMP_TARGET}.tar.gz"
	download_uri_per_arch "${BIN_ARCH_URI_AMD64}" "${BIN_ARCH_URI_ARM64}" "${BIN_ARCH_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${BIN_ARCH_TMP_FILE}" "tar" "${TEMP_TARGET}"
	remove_item "${BIN_ARCH_TMP_FILE}"
	move_item_per_arch "${TEMP_TARGET}/stdiscosrv-linux-amd64-v${INSTALL_VERSION}" "${TEMP_TARGET}/stdiscosrv-linux-arm64-v${INSTALL_VERSION}" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
symlink_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC}" "${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
