#!/bin/sh

################################################################################
#
#  telegram-install
#
#  Install/Update Telegram Desktop for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://telegram.org/
#
#  Usage:
#    telegram-install [<version>]
#
#  Example:
#    telegram-install
#    telegram-install 6.7.7
#    telegram-install v6.7.7
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="telegramdesktop"
GITHUB_REPO="tdesktop"
PROGRAM_ID="telegram"
PROGRAM_EXEC="Telegram"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env_desktop "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_ARCH_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/tsetup.${INSTALL_VERSION}.tar.xz"
	BIN_ARCH_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/tsetup.${INSTALL_VERSION}.tar.xz"
	BIN_ARCH_TMP_FILE="${TEMP_TARGET}.tar.xz"
	download_uri_per_arch "${BIN_ARCH_URI_AMD64}" "${BIN_ARCH_URI_ARM64}" "${BIN_ARCH_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${BIN_ARCH_TMP_FILE}" "tar" "${TEMP_TARGET}"
	remove_item "${BIN_ARCH_TMP_FILE}"
	move_item "${TEMP_TARGET}/Telegram" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
copy_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC}" "${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
install_desktop "${PROGRAM_ID}" "${CTXDIR}" "${DESKTOP_ROOT}" "${ICON_ROOT}"
