#!/bin/sh

################################################################################
#
#  thunderbird-install
#
#  Install/Update Mozilla Thunderbird for current user. This also works as a version manager.
#
#  Homepage: https://www.thunderbird.net/
#
#  Usage:
#    thunderbird-install <version>
#
#  Example:
#    thunderbird-install 147.0.1
#    thunderbird-install v147.0.1
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

# Application info
PROGRAM_ID="thunderbird"
PROGRAM_EXEC="thunderbird"

set -ex

# Determine version to install
if [ -z "$1" ]; then
	echo "Error: Version must be explicitly specified"
	exit 1
else
	LATEST_VERSION="$1"
fi
LATEST_VERSION="${LATEST_VERSION#v}"

# Installation environment
USERID="$(id -u)"
ARCH="$(uname -m)"
if [ "${USERID}" -eq 0 ]; then
	INSTALL_ROOT="/usr/local/share/${PROGRAM_ID}"
	SYSTEM_BIN_ROOT="/usr/local/bin"
else
	INSTALL_ROOT="${HOME}/.local/share/${PROGRAM_ID}"
	SYSTEM_BIN_ROOT="${HOME}/.local/bin"
fi
INSTALL_TARGET="${INSTALL_ROOT}/${PROGRAM_ID}-v${LATEST_VERSION}"
ACTIVE_TARGET="${INSTALL_ROOT}/active-release"

if [ ! -d "${INSTALL_ROOT}" ]; then
	mkdir -p "${INSTALL_ROOT}"
fi
if [ ! -d "${SYSTEM_BIN_ROOT}" ]; then
	mkdir -p "${SYSTEM_BIN_ROOT}"
fi

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_ARCH_URI_AMD64="https://ftp.mozilla.org/pub/thunderbird/releases/${LATEST_VERSION}/linux-x86_64/en-US/thunderbird-${LATEST_VERSION}.tar.xz"
	BIN_ARCH_URI_ARM64=""
	BIN_ARCH_TMP_FILE="/tmp/${PROGRAM_ID}-v${LATEST_VERSION}.tar.xz"

	if [ "${ARCH}" = "x86_64" ] || [ "${ARCH}" = "amd64" ]; then
		wget "${BIN_ARCH_URI_AMD64}" -O "${BIN_ARCH_TMP_FILE}"
	elif [ "${ARCH}" = "aarch64" ] || [ "${ARCH}" = "arm64" ]; then
		echo "Unsupported architecture: ${ARCH}"
		exit 1
	else
		echo "Unsupported architecture: ${ARCH}"
		exit 1
	fi

	TEMP_TARGET="/tmp/${PROGRAM_ID}-v${LATEST_VERSION}"
	mkdir "${TEMP_TARGET}"
	tar -x -v -f "${BIN_ARCH_TMP_FILE}" -C "${TEMP_TARGET}"
	rm "${BIN_ARCH_TMP_FILE}"
	mv "${TEMP_TARGET}/thunderbird" "${INSTALL_TARGET}"
	rm -r "${TEMP_TARGET}"
fi

# Set active release
if [ -f "${ACTIVE_TARGET}" ] || [ -d "${ACTIVE_TARGET}" ] || [ -L "${ACTIVE_TARGET}" ]; then
	rm -r "${ACTIVE_TARGET}"
fi
ln -s "${INSTALL_TARGET}" "${ACTIVE_TARGET}"

# Create symlink for quick access
ACTIVE_TARGET_BIN="${ACTIVE_TARGET}/${PROGRAM_EXEC}"
SYSTEM_BIN_TARGET_BIN="${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
if [ -f "${ACTIVE_TARGET_BIN}" ]; then
	if [ -f "${SYSTEM_BIN_TARGET_BIN}" ] || [ -d "${SYSTEM_BIN_TARGET_BIN}" ] || [ -L "${SYSTEM_BIN_TARGET_BIN}" ]; then
		rm -r "${SYSTEM_BIN_TARGET_BIN}"
	fi
	ln -s "${ACTIVE_TARGET_BIN}" "${SYSTEM_BIN_TARGET_BIN}"
fi
