#!/bin/sh

################################################################################
#
#  uv-install
#
#  Install/Update UV for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://docs.astral.sh/uv/
#
#  Usage:
#    uv-install [<version>]
#
#  Example:
#    uv-install
#    uv-install 0.11.11
#    uv-install v0.11.11
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="astral-sh"
GITHUB_REPO="uv"
PROGRAM_ID="uv"
PROGRAM_EXEC="uv"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_ARCH_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/${INSTALL_VERSION}/uv-x86_64-unknown-linux-gnu.tar.gz"
	BIN_ARCH_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/${INSTALL_VERSION}/uv-aarch64-unknown-linux-gnu.tar.gz"
	BIN_ARCH_TMP_FILE="${TEMP_TARGET}.tar.gz"
	download_uri_per_arch "${BIN_ARCH_URI_AMD64}" "${BIN_ARCH_URI_ARM64}" "${BIN_ARCH_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${BIN_ARCH_TMP_FILE}" "tar" "${TEMP_TARGET}"
	remove_item "${BIN_ARCH_TMP_FILE}"
	move_item_per_arch "${TEMP_TARGET}/uv-x86_64-unknown-linux-gnu" "${TEMP_TARGET}/uv-aarch64-unknown-linux-gnu" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
symlink_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC}" "${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
cat << EOF > "${INSTALL_ROOT}/env.sh"
export UV_INSTALL_DIR="${ACTIVE_TARGET}"
export UV_PYTHON_INSTALL_DIR="${INSTALL_ROOT}/python"
export UV_TOOL_DIR="${INSTALL_ROOT}/tool"
EOF
create_dir "${INSTALL_ROOT}/python"
make_all_access "${INSTALL_ROOT}/python"
create_dir "${INSTALL_ROOT}/tool"
make_all_access "${INSTALL_ROOT}/tool"
append_text_idempotent "# uv" "${USER_PROFILE_RC}"
append_text_idempotent ". \"${INSTALL_ROOT}/env.sh\"" "${USER_PROFILE_RC}"
