#!/bin/sh

################################################################################
#
#  vscode-install
#
#  Install/Update Visual Studio Code for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://code.visualstudio.com/
#
#  Usage:
#    vscode-install [<version>]
#
#  Example:
#    vscode-install
#    vscode-install 1.111.0
#    vscode-install v1.111.0
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="microsoft"
GITHUB_REPO="vscode"
PROGRAM_ID="vscode"
PROGRAM_EXEC="code"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env_desktop "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_ARCH_URI_AMD64="https://update.code.visualstudio.com/${INSTALL_VERSION}/linux-x64/stable"
	BIN_ARCH_URI_ARM64="https://update.code.visualstudio.com/${INSTALL_VERSION}/linux-arm64/stable"
	BIN_ARCH_TMP_FILE="${TEMP_TARGET}.tar.gz"
	download_uri_per_arch "${BIN_ARCH_URI_AMD64}" "${BIN_ARCH_URI_ARM64}" "${BIN_ARCH_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${BIN_ARCH_TMP_FILE}" "tar" "${TEMP_TARGET}"
	remove_item "${BIN_ARCH_TMP_FILE}"
	move_item_per_arch "${TEMP_TARGET}/VSCode-linux-x64" "${TEMP_TARGET}/VSCode-linux-arm64" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
copy_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC}" "${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
install_desktop "${PROGRAM_ID}" "${CTXDIR}" "${DESKTOP_ROOT}" "${ICON_ROOT}"
