#!/bin/sh

################################################################################
#
#  waterfox-install
#
#  Install/Update Waterfox for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://www.waterfox.com/
#
#  Usage:
#    waterfox-install [<version>]
#
#  Example:
#    waterfox-install
#    waterfox-install 6.7.7
#    waterfox-install v6.7.7
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="BrowserWorks"
GITHUB_REPO="waterfox"
PROGRAM_ID="waterfox"
PROGRAM_EXEC="waterfox"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env_desktop "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_ARCH_URI_AMD64="https://cdn.waterfox.com/waterfox/releases/${INSTALL_VERSION}/Linux_x86_64/waterfox-${INSTALL_VERSION}.tar.bz2"
	BIN_ARCH_URI_ARM64="https://cdn.waterfox.com/waterfox/releases/${INSTALL_VERSION}/Linux_arm64/waterfox-${INSTALL_VERSION}.tar.bz2"
	BIN_ARCH_TMP_FILE="${TEMP_TARGET}.tar.gz"
	download_uri_per_arch "${BIN_ARCH_URI_AMD64}" "${BIN_ARCH_URI_ARM64}" "${BIN_ARCH_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${BIN_ARCH_TMP_FILE}" "tar" "${TEMP_TARGET}"
	remove_item "${BIN_ARCH_TMP_FILE}"
	move_item "${TEMP_TARGET}/waterfox" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Set active release
if [ -f "${ACTIVE_TARGET}" ] || [ -d "${ACTIVE_TARGET}" ] || [ -L "${ACTIVE_TARGET}" ]; then
	rm -r "${ACTIVE_TARGET}"
fi
cp -r "${INSTALL_TARGET}" "${ACTIVE_TARGET}"

# Create symlink for quick access
ACTIVE_TARGET_BIN="${ACTIVE_TARGET}/${PROGRAM_EXEC}"
SYSTEM_BIN_TARGET_BIN="${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
if [ -f "${ACTIVE_TARGET_BIN}" ]; then
	if [ -f "${SYSTEM_BIN_TARGET_BIN}" ] || [ -d "${SYSTEM_BIN_TARGET_BIN}" ] || [ -L "${SYSTEM_BIN_TARGET_BIN}" ]; then
		rm -r "${SYSTEM_BIN_TARGET_BIN}"
	fi
	ln -s "${ACTIVE_TARGET_BIN}" "${SYSTEM_BIN_TARGET_BIN}"
fi

# Finalize install
copy_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC}" "${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
install_desktop "${PROGRAM_ID}" "${CTXDIR}" "${DESKTOP_ROOT}" "${ICON_ROOT}"
